### ISSUE TITLE
Site can't find solr 

### ISSUE THREAD

**Issue by davekopecek** [blinkreaction/drude#169]
I'm unable to get the drude-d7-testing project to recognize apache solr

Per  apache-solr.md I added a solr node to docker-compose.yml:

``` yml
 # Solr node
 # Uncomment the service definition section below to start using Solr.
 solr:
   hostname: solr
   image: blinkreaction/drupal-solr:3.x-stable
   environment:
     - DOMAIN_NAME=solr.drupal7.drude
```

Downloaded and enabled `apachesolr-7.x-1.x-dev` and setup a server at `admin/config/search/apachesolr/settings/add` with the url

```
    http://solr.drupal7.drude:8983/solr  
```

Testing the connection from `admin/config/search/apachesolr/settings/solr/edit`
gives me the warning _Your site was unable to contact the Apache Solr server._

Output of `dsh ps`

```
        Name                       Command               State        Ports
---------------------------------------------------------------------------------
druded7testing_cli_1    /opt/startup.sh gosu root  ...   Up      22/tcp, 9000/tcp
druded7testing_db_1     /entrypoint.sh mysqld            Up      3306/tcp
druded7testing_solr_1   java -jar start.jar              Up      8983/tcp
druded7testing_web_1    /opt/startup.sh apache2 -D ...   Up      443/tcp, 80/tcp
```
