### ISSUE TITLE
Circular dependency - web, cli, browser

### ISSUE THREAD

**Issue by frankcarey** [blinkreaction/drude#43]
When uncommenting the seleniume2/browser containers in the docker-compose.yml file, docker complains about the circular dependency.  Here is a copy of the file.

``` Yaml
# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

# Web node
web:
  hostname: web
  image: blinkreaction/drupal-apache:2.2
  ports:
    - "80"
    - "443"
    # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
    #- 192.168.10.10:80:80 
    #- 192.168.10.10:443:443
  environment:
    - VIRTUAL_HOST=devinci.local
  volumes_from:
    - cli
  links:
    - cli
    - db
    # Uncomment this and the memcached service definition below to start using memcached.
    #- memcached
  environment:
    - VIRTUAL_HOST=hello-world.drude

# DB node
db:
  hostname: db
  image: blinkreaction/drupal-mysql:5.5
  ports:
    - "3306"
    # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
    #- 192.168.10.10:3306:3306
  # DB configuration
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
  volumes:
     # MySQL configuration overrides
     - "./.drude/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"

# CLI node
# Used for all console commands and tools.
cli:
  hostname: cli
  image: blinkreaction/drupal-cli:php-5.6
  volumes:
    # Host SSH keys mappings.
    # We try to map both options. The startup.sh script in cli container will decide which one to use.
    - /.ssh:/.ssh-b2d  # boot2docker-vagrant
    - ~/.ssh:/.ssh   # Linux
    # PHP configuration overrides
    - "./.drude/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
    #- "./.drude/etc/php5/php-cli.ini:/etc/php5/fpm/conf.d/z_php.ini"
    # Project root folder mapping
    - ".:/var/www"
  links:
    - db
    # Uncomment this and the browser service definition below to start using selenium2.
    - browser

# Memcached node
# Uncomment the service definition section below and the link in the web service above to start using memcached.
# memcached:
#   hostname: memcached
#   image: memcached
#   environment:
#     # Memcached memory limit in megabytes
#     - MEMCACHED_MEMORY_LIMIT=128

# ngrok node
# Uncomment the service definition section below to start using ngrok for sharing your local web server with the world.
# share:
#   hostname: share
#   image: fnichol/ngrok
#   ports:
#     - "4040"
#     # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
#     #- 192.168.10.10:4040:4040
#   links:
#     - web:http

# selenium2 node
# Uncomment the service definition section below and the link in the web service above to start using selenium2 driver for Behat tests requiring JS support.
browser:
   hostname: browser
   image: selenium/standalone-chrome
   links:
     - web
   ports:
     - "4444"
```
