### ISSUE TITLE
Drude Installer conflicts with custom boot2docker VM vhost_proxy setting

### ISSUE THREAD

**Issue by frankcarey** [blinkreaction/drude#44]
The drude installer will install the Vagrantfile and vagrant.yml (one level above), but the vhost_proxy setting causes port conflicts on 443 with the way the default docker-compose.yml is set.

See more details on the issue I opened upstream https://github.com/blinkreaction/boot2docker-vagrant/issues/31
### Example docker-compose.yml

``` Yaml
# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

# Web node
web:
  hostname: web
  image: blinkreaction/drupal-apache-php:2.2-5.5
  ports:
    - "80:80"
    - "443:443"
    # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
    #- 192.168.10.10:80:80 
    #- 192.168.10.10:443:443 
  volumes:
    # PHP configuration overrides
    - "./.docker/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
    # Project root folder mapping
    - &project_root ".:/var/www"
  links:
    - db
    # Uncomment this and the memcached service definition below to start using memcached.
    #- memcached

# DB node
db:
  hostname: db
  image: blinkreaction/mysql:5.5
  ports:
    - "3306:3306"
    # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
    #- 192.168.10.10:3306:3306
  # DB configuration
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
  volumes:
     # MySQL configuration overrides
     - "./.docker/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
     # Permanent DB data storage
     - /var/lib/mysql

# CLI node
# Used for all console commands and tools.
cli:
  hostname: cli
  image: blinkreaction/drupal-cli
  volumes:
    # PHP configuration overrides
    - "./.docker/etc/php5/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"
    # Project root folder mapping
    - *project_root
    # Host SSH keys mapping. Uncomment one of the lines below based on your setup.
    - /.ssh:/.ssh   # boot2docker-vagrant
    #- ~/.ssh:/.ssh  # Linux
  links:
    - db
    - web
    # Uncomment this and the browser service definition below to start using selenium2.
    - browser

# Memcached node
# Uncomment the service definition section below and the link in the web service above to start using memcached.
# memcached:
#   hostname: memcached
#   image: memcached
#   environment:
#     # Memcached memory limit in megabytes
#     - MEMCACHED_MEMORY_LIMIT=128

# ngrok node
# Uncomment the service definition section below to start using ngrok for sharing your local web server with the world.
# share:
#   hostname: share
#   image: fnichol/ngrok
#   ports:
#     - "4040:4040"
#     # Use IP based mapping when working with multiple projects. See docs (^^) for more details.
#     #- 192.168.10.10:4040:4040
#   links:
#     - web:http

# selenium2 node
# Uncomment the service definition section below and the link in the web service above to start using selenium2 driver for Behat tests requiring JS support.
browser:
  hostname: browser
  image: selenium/standalone-chrome
  links:
    - web
  ports:
    - "4444:4444"
```
### Recommended fix:

Only install an appropriate (pegged) version of the custom boot2docker so that the vm installed is ensured to be compatible out of the box. 

Note: From my other tinkering, it looks like the newest versions of the docker-composer.yml file in `develop` remove the hardcoding of the host port, but they require vhost_proxy to be set to true so the random ports can be identified. There are also other issues I'm hitting when using the develop branch, so  master should be fixed for now until the new stuff is resolved.
